apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-efs 
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-06270d5a3c6e19311
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-efs
spec:
  volumeName: expense-efs 
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi    
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  labels:
    purpose: efs-static 
spec:
  containers:
  - name: nginx
    image: nginx 
    volumeMounts: # docker run -v hostpath:containerpath 
    - name: expense-efs  
      mountPath: /usr/share/nginx/html 
  volumes:
  - name: expense-efs  
    persistentVolumeClaim:
      claimName: expense-efs      
