apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic  
spec:
  storageClassName: "efs-expense" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi 