apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic  
spec:
  storageClassName: "efs-expense" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi 
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic 
  labels:
    purpose: efs-dynamic 
spec:
  containers:
  - name: nginx
    image: nginx 
    volumeMounts: # docker run -v hostpath:containerpath 
    - name: expense-efs  
      mountPath: /usr/share/nginx/html 
  volumes:
  - name: efs-dynamic  
    persistentVolumeClaim:
      claimName: efs-dynamic      
---
kind: Service 
apiVersion: v1
metadata:
  name: nginx 
spec:
  type: LoadBalancer 
  selector:
    purpose: efs-dynamic 
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port       
    nodePort: 30007  